---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kavita
  namespace: &namespace self-hosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: volsync
      namespace: volsync-system
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/volsync
    - ../../../../components/keda/nfs-scaler
  interval: 1h
  path: ./kubernetes/apps/self-hosted/kavita/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
