---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app bookorbit
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        PODCAST_ENCRYPTION_KEY: "{{ .PODCAST_ENCRYPTION_KEY }}"
        SETUP_BOOTSTRAP_TOKEN: "{{ .SETUP_BOOTSTRAP_TOKEN }}"
  dataFrom:
    - extract:
        key: *app
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret bookorbit-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *secret
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: bookorbit
    - extract:
        key: cloudnative_pg
