---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app freshrss
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        ADMIN_API_PASSWORD: "{{ .ADMIN_API_PASSWORD }}"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_CLIENT_CRYPTO_KEY: "{{ .OIDC_CLIENT_CRYPTO_KEY }}"
  dataFrom:
    - extract:
        key: *app
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret freshrss-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *secret
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: freshrss
    - extract:
        key: cloudnative_pg
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mkfd
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: mkfd
    creationPolicy: Owner
    template:
      data:
        PASSKEY: "{{ .PASSKEY }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: mkfd
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fivefilters
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: fivefilters
    creationPolicy: Owner
    template:
      data:
        FTR_ADMIN_PASSWORD: "{{ .FTR_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: fivefilters
