---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1yu7mnjc625umxhznmkc8yc3mhgzn9g9n54jwarrp3l23ja90m54q0l5yw4"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1yu7mnjc625umxhznmkc8yc3mhgzn9g9n54jwarrp3l23ja90m54q0l5yw4"
stores:
  yaml:
    indent: 2
