---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ${APP}
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mccloud/subgen
              tag: 2026.04.1-cpu@sha256:82bb39371acc8e5befe51901278260863b5174fc223c502e2a5ace769eebcb06
            env:
              TZ: "${TIMEZONE}"

              TRANSCRIBE_DEVICE: cpu
              WHISPER_MODEL: large-v3-turbo.en
              CONCURRENT_TRANSCRIPTIONS: 2
              WHISPER_THREADS: 20
              COMPUTE_TYPE: auto
              CLEAR_VRAM_ON_COMPLETE: false

              PROCESS_ADDED_MEDIA: true
              PROCESS_MEDIA_ON_PLAY: true
              PLEX_QUEUE_NEXT_EPISODE: true
              PLEX_QUEUE_SEASON: true
              PLEX_QUEUE_SERIES: true

              SKIP_IF_TARGET_SUBTITLES_EXIST: true
              SKIP_IF_INTERNAL_SUBTITLES_LANGUAGE: eng

              WEBHOOK_PORT: &port 9000
              PUID: 568
              PGID: 568
              DEBUG: true
              MODEL_PATH: /models

              PLEX_SERVER: http://${PLEX_IP}:32400

            envFrom:
              - secretRef:
                  name: *app

            resources:
              requests:
                cpu: 4000m
                memory: 4Gi
              limits:
                memory: 8Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      models:
        type: emptyDir
      media:
        type: nfs
        server: ${NAS_IP}
        path: ${NAS_PATH}/data
        globalMounts:
          - path: /mnt/data
