# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:XSUJ7RH4kUthjnHzxTUsBqrPrqI+jE16uUs+1v9sA0K2j/OVXDWueg==,iv:aYshKWwmGZ9gwFWBsBPwewK1lI/602yZPRkV/zhRYLw=,tag:f9vVZCVnFpyoDkdjR/hCwA==,type:str]
sops:
  age:
    - recipient: age1yu7mnjc625umxhznmkc8yc3mhgzn9g9n54jwarrp3l23ja90m54q0l5yw4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUXRVc1MrMXo2UjJHZHFa
        TG1DR1hUUi92SmptQlRoSC9PWm9CN0MvYkRvCkp3R1RZRFh3UGFWVm1vdStCZE50
        ckJJQnlrOUFOTEpGTWduOVVtdVRPUkEKLS0tIDg3SXhPYmdKZXBmZXZnSXBKNUhW
        VWRBOEo0NEE0T3pjbndTVzRiZ1NrRmsK9t1Q9jeX4ZvWtst+L79ilU4d64YzHdJW
        HJPN7q2d5DC+fRZEnfODmdZ7IaLz0wv6DTjDZ07dusHDbdmvEmIm4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T16:00:29Z"
  mac: ENC[AES256_GCM,data:+zq5g08EySrRPSbau7mGXLZzK2CKEYJ+Ybms1LodFVvqwr+xy9JynrxvI7F2SHQl1XL9r8vHqNELRdNDEzI8IFzGdKBUr5ceKA2Few0CW9oLibA49IPA8/wwbimjm7sqL4WwhQ2Cyu3HAnFNHO4vyy6jGhAwDCyGwfQaZG670Q4=,iv:CMwsgPO9fcgVULoXh43FFYDGYo++nrzfFuLgeVy0w7E=,tag:n4+b8eTz+I/MKr573Lh5Dg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
