---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}-dst"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:=10Gi}"
  storageClassName: "openebs-zfs-${VOLSYNC_RECORD_SIZE:-128k}"
