---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled

  values:
    controllers:
      drawio:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: jgraph/drawio
              tag: latest@sha256:d46e87bcd015763f0fbaef9cd62b9181ff69052fcf6d12b24e4d879100e22980
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - '{{ .Release.Name }}.${SECRET_DOMAIN}'
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs: [{}]
        annotations:
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/name: Draw.io
          gethomepage.dev/group: Tools
          gethomepage.dev/icon: mdi-draw-pen
          gethomepage.dev/app: drawio
