---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app appflowy-gotrue
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres-appflowy-rw:5432/{{ .POSTGRES_DB }}?search_path=auth"
        GOTRUE_ADMIN_EMAIL: "{{ .GOTRUE_ADMIN_EMAIL }}"
        GOTRUE_ADMIN_PASSWORD: "{{ .GOTRUE_ADMIN_PASSWORD }}"
        GOTRUE_JWT_SECRET: "{{ .GOTRUE_JWT_SECRET }}"
        GOTRUE_SAML_PRIVATE_KEY: "{{ .GOTRUE_SAML_PRIVATE_KEY }}"
        GOTRUE_SMTP_HOST: "{{ .EMAIL_SERVER }}"
        GOTRUE_SMTP_PORT: "465"
        GOTRUE_SMTP_USER: "{{ .EMAIL_USER }}"
        GOTRUE_SMTP_PASS: "{{ .EMAIL_PASS }}"
        GOTRUE_SMTP_ADMIN_EMAIL: "{{ .EMAIL_FROM }}"
  dataFrom:
    - extract:
        key: appflowy
    - extract:
        key: email
