---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: browserless
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: browserless-secret
    creationPolicy: Owner
    template:
      data:
        BROWSERLESS_TOKEN: '{{ .BROWSERLESS_TOKEN }}'
  dataFrom:
    - extract:
        key: browserless
