---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app appflowy-web
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: appflowyinc/appflowy_web
              tag: 0.9.99@sha256:4622a75c51d35659b2f0fb265400b6cd2ae0cbb49dbe1aa37cad1089c95391bf
            env:
              AF_BASE_URL: "https://appflowy.${SECRET_DOMAIN}"
              AF_GOTRUE_URL: "https://appflowy.${SECRET_DOMAIN}/gotrue"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 80
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
            resources:
              requests:
                cpu: 100m
    service:
      main:
        controller: *app
        ports:
          http:
            port: *port
    route:
      *app :
        enabled: true
        hostnames: ["appflowy.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: *app
                port: *port
