# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:vuVt+jtO48HHJOPiz1FIu5c7lyH7gha0vcEjU0TVmMU=,iv:SXJEYJQFLBgpUWUzLvAqIA0dKrBSjRnWCOxRtkOnSJw=,tag:hYYrkpiO4ANw2MOGkeE77Q==,type:str]
sops:
  age:
    - recipient: age1yu7mnjc625umxhznmkc8yc3mhgzn9g9n54jwarrp3l23ja90m54q0l5yw4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q1hqRmtuQWpjN2V1cStq
        cjJaVGZQTExJdkRtcTZua3NjZ01RQjdZVmdvClo1UVV0ZzZ2L3FrQ2RMV3N0R0NS
        Qk5GMmI1M05aUmhjVFVTOFNIbm1DcW8KLS0tIHRSdlYrYjJDczd1a0c4cytXNEk3
        cEFWYkVFV21rNytHbm1pb1RtZm5jNUkKoupJ6mR2K14Nn29OF/2OtVDlhWtx76oe
        ZdA0+pJUL2LTZc1KEZ2HbFarkmz1FMcsOUFtVU40o48ZLQRe5P6mCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T16:00:29Z"
  mac: ENC[AES256_GCM,data:q/82MGKoQSptwKMYaenNLq4sWEU0xim5KI6kSUR4xsPkZAwR7qW6zfAZPSbxhuuzyBP8h3xfe4nTsIUyPt85lPWb1odTAfjt1xrxmJ0wWp1zpZuUCbtNv1fqdTlbQdezQEVHAbr+pZ7PIi3vy62hQbhl5K2CzD4fd/i5biZbayE=,iv:YEZr6yJz3/IaaTBYJAdUJpEj91UMigtyRX20s0TpTn0=,tag:ZlesJ6fWFz9tY6ormqWIRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
