---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app appflowy-worker
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: appflowyinc/appflowy_worker
              tag: 0.9.117@sha256:a9eee13453155ddfb6131ad8d5ccf499c0e87b8f287ed8c62a519267d7c7586e
            env:
              APPFLOWY_WORKER_REDIS_URL: "redis://appflowy-redis:6379"
              APPFLOWY_WORKER_ENVIRONMENT: "production"
              APPFLOWY_WORKER_IMPORT_TICK_INTERVAL: "30"
              APPFLOWY_S3_USE_MINIO: "true"
              APPFLOWY_S3_CREATE_BUCKET: "true"
              APPFLOWY_S3_MINIO_URL: "http://appflowy-minio:9000"
              APPFLOWY_S3_BUCKET: "appflowy"
              APPFLOWY_S3_REGION: "us-east-1"
              APPFLOWY_INDEXER_ENABLED: "true"
            envFrom:
              - secretRef:
                  name: *app
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
