---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent
  namespace: &namespace downloads
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/volsync
    - ../../../../components/keda/nfs-scaler
  dependsOn:
    - name: keda
      namespace: observability
    - name: volsync
      namespace: volsync-system
  interval: 1h
  retryInterval: 2m
  path: ./kubernetes/apps/downloads/qbittorrent/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: qbittorrent
      VOLSYNC_CAPACITY: 2Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
