---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app "${APP}"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_DBNAME: *app
        INIT_POSTGRES_HOST: postgres-cluster-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *app
        INIT_POSTGRES_PASS: &dbpass "{{ .DB_PASSWORD }}"
        POSTGRES_PASSWORD: *dbpass

        # Mailer
        MAILER_ENABLED: "true"
        MAILER_HOST: "{{ .EMAIL_SERVER }}"
        MAILER_PORT: "587"
        MAILER_SECURITY: starttls
        MAILER_AUTH_USER: "{{ .EMAIL_USER }}"
        MAILER_AUTH_PASSWORD: "{{ .EMAIL_PASS }}"
        MAILER_NOREPLY_NAME: Joplin
        MAILER_NOREPLY_EMAIL: "{{ .EMAIL_FROM }}"
  dataFrom:
    - extract:
        key: *app
    - extract:
        key: email
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret joplin-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *secret
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative_pg
