# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:50eUrp6N9QLEjHg/2HJromy0pNNCPG3fwvQOOicPbE1UY4E6ylprRgkcsv7aHOiGBZtEcXFyg2Q3jrK/+/JkSrKRTowVCKYW76zQ7WBQFBP+4e/mP6DKSbKMYq8yCPvOy9Z/s8E4EiMGFVk7eEZEP8tPYnBSyB69lL4xi8pFa/Qxco7qRKg0hRfqr+gNrsYs1qUotF5EELGSi66W+OVDSe4NivRPnRLRnu5g4NzR09TxQpqs,iv:VyNJXlK230eWBwzQFO5Nh1X3YzzI4RYmfPaB1fOBnVA=,tag:wd9MbAkfR0Ln0QrL09l8HA==,type:str]
sops:
  age:
    - recipient: age1yu7mnjc625umxhznmkc8yc3mhgzn9g9n54jwarrp3l23ja90m54q0l5yw4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYnF6SERLeTRmb0QyUjNY
        NVp0QmNLb2xnYW1xQ21QZ2pvU0t2ZVhwdUJnCmwxMDZkYlk2MnRGZEZTS0RiTHBI
        SVNNdUFVOWN0c1N5TzVTNEptMXJseVkKLS0tIGxnNXRDSXIwZ054d2oyOCtXRWwy
        NUtSZkNjM2JBSkZMUVJ1czMrVWNNSEkKahwJ42u9h1dwebSVN8tt8w8GbvDvNcEg
        T8ZKq/Ps/jZOyPxmgh30iOSMRrsouif5O+fNMna63u1ZHhp4RS4flw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T16:00:29Z"
  mac: ENC[AES256_GCM,data:j4kT0hlmXtxNZJa9+NYE0dMRSg2MfZ0gO0y4b0ekq54XQJnYkCwZED6Xy2+NRH9hOF0f4VsuvSxL61re/oYHE7WxBE98DqR9a10r0WXlArc4FKmMRwp1HEFamFIR6icVR8psXY2m1V1agHI/IQS7rt7ktGPTjDaa5kLcpjZDaKE=,iv:BRhxqUkHTQ1XDKQh8IjRlgdpIefw3WMIewhjRZf8JDs=,tag:PIQXkP9DxdYLa5iGSFZt8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
