---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: home-assistant
addressType: IPv4
ports:
  - name: http
    port: ${HASS_PORT}
    protocol: TCP
endpoints:
  - addresses:
      - ${HASS_IP}
