---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Home
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/icon: home-assistant.svg
    gethomepage.dev/widget.type: homeassistant
    gethomepage.dev/widget.url: http://${HOMEASSISTANT_IP}:8123
    gethomepage.dev/widget.key: '{{`{{HOMEPAGE_VAR_HA_TOKEN}}`}}'
spec:
  hostnames:
    - ${APP}.${SECRET_DOMAIN}
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: external-services
          port: 8123
