---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Home
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/icon: home-assistant.svg
    gethomepage.dev/widget.type: homeassistant
    gethomepage.dev/widget.url: http://home-assistant.external-services.svc.cluster.local:8123
    gethomepage.dev/widget.key: '{{`{{HOMEPAGE_VAR_HA_TOKEN}}`}}'
spec:
  hostnames:
    - ${APP}.${SECRET_DOMAIN}
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
