---
apiVersion: v1
kind: Service
metadata:
  name: ${APP}
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for external endpoints
  ports:
    - port: 8123
      protocol: TCP
      targetPort: 8123
