---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Home
    gethomepage.dev/name: Plex
    gethomepage.dev/icon: plex.svg
    gethomepage.dev/widget.type: plex
    gethomepage.dev/widget.url: http://plex.external-services.svc.cluster.local:32400/web/index.html
    gethomepage.dev/widget.key: '{{`{{HOMEPAGE_VAR_PLEX_TOKEN}}`}}'
spec:
  hostnames:
    - ${APP}.${SECRET_DOMAIN}
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: external-services
          port: 32400
