---
apiVersion: v1
kind: Service
metadata:
  name: ${APP}
  labels:
    app: ${APP}
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for external endpoints
  ports:
    - name: http
      port: 32400
      protocol: TCP
      targetPort: 32400
