---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app appflowy-minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: "{{ .AWS_ACCESS_KEY }}"
        MINIO_ROOT_PASSWORD: "{{ .AWS_SECRET }}"
  dataFrom:
    - extract:
        key: appflowy
