---
# yaml-language-server: $schema=https://schemas.tholinka.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-immich
spec:
  instances: 0  # Scale down to 0
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-standard-bookworm@sha256:8bcc3eb5b0b2dd7ad91c3c57eadc0df37148f28be16fc8062ed5eb29a2a4a4b7
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  managed:
    services:
      disabledDefaultServices: ['ro', 'r']
  storage:
    size: 5Gi
    storageClass: openebs-zfs-128k  # Using existing OpenEBS hostpath
  superuserSecret:
    name: immich-cnpg-secret
  enableSuperuserAccess: true
  resources:
    requests:
      cpu: 500m
      memory: 8Gi
    limits:
      hugepages-2Mi: 1Gi
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  probes:
    startup:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 30

