---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ${APP}
  labels:
    kubernetes.io/service-name: ${APP}
addressType: IPv4
ports:
  - name: https
    port: 443
    protocol: TCP
endpoints:
  - addresses:
      - ${NEXTCLOUD_IP}
