---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/name: Nextcloud
    gethomepage.dev/icon: nextcloud.svg
    gethomepage.dev/widget.type: nextcloud
    gethomepage.dev/widget.url: https://${APP}.${SECRET_DOMAIN}
    gethomepage.dev/widget.key: '{{`{{HOMEPAGE_VAR_NEXTCLOUD_TOKEN}}`}}'
spec:
  hostnames:
    - ${APP}.${SECRET_DOMAIN}
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: external-services
          port: 80
