# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:UTq9CRvdhPUUIcvnUL+ds2eltnFI5ITWSGbyCvMkuG35g616Y6ejqA==,iv:SgkLEw5BaJR+6OMpkPBXXjJJs4bD7mpb6D9QLOJfuyk=,tag:RBrF8jSfEqb7/e0cU/xSyQ==,type:str]
sops:
  age:
    - recipient: age1yu7mnjc625umxhznmkc8yc3mhgzn9g9n54jwarrp3l23ja90m54q0l5yw4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbWR0UnhsQzc3UzlldXYr
        N2lIdm16T0IwUWhFWTc2NkhiMURyNmsyMzAwCjF5QTd4VEl4cHFycDM3VjQrdk9G
        ZkM5Y2ZXUm5MQzF4YmZsSk5lU01jOWMKLS0tIFV4VmJtUEVVTnc0c3hZOVpUNjJq
        VzNqM2pBdU95aG1RaFFUS3ZPNCszSVkKVLF7F5nbr4ajDxkb3Fqt3i/lrLqjNPON
        HSRzoyMbUUnoxmoSnQHpbdleUfvXFV+t5aUGz7hSIwJ6tzb85SNpww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T16:00:29Z"
  mac: ENC[AES256_GCM,data:ATr0lk5l1w3gsGR2NjInKYqaJTKZcl/SlLY6NDYybDglG6FxSr2oGB7XUHNyVSsfmklqyPMiu+mXsfiilxyKrzzCUULyQlxcB+vjgRAbeR1UoKa1r1Eg0DR7A5EayIk71676IR+ZrSSEiCkh2L1b7sqna1Uy1xIjii40CqkyPrs=,iv:b86MgvUPEdSbrBxxySLbjrMvlSfBH0TbnZJ5t5l8bVY=,tag:z5FoKXTfFVrhMqxhpH+8eg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
