# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.6:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.6"
  - "cluster.local"
  - "cluster.tostava.com"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k3s"
    ipAddress: "192.168.1.5"
    installDiskSelector:
      wwid: "naa.5002538e01126c0e"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/d4fb6a885cdd5215ecf2c3f3205dc8139354bdd04e73bf3799b31ec23d4b35e9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "94:40:c9:1e:82:c0"
        dhcp: false
        addresses:
          - "192.168.1.5/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
        vip:
          ip: "192.168.1.6"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-features.yaml"
  - "@./patches/global/machine-kernel-modules.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

