---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app appflowy-ai
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: appflowyinc/appflowy_ai
              tag: 0.9.100@sha256:cac908609b2c3ac13deebe76a58fb23174c53fcf9967a9fd3614df02c458c9e7
            env:
              AI_SERVER_PORT: &port 5001
              DEFAULT_AI_MODEL: gpt-4.1-mini # Make sure the model is available in your OpenAI account
              DEFAULT_AI_COMPLETION_MODEL: gpt-4.1-mini # Make sure the model is available in your OpenAI account
              AI_REDIS_URL: "redis://dragonfly-appflowy:6379"
              AI_MINIO_URL: https://appflowy.${SECRET_DOMAIN}/minio
              AI_APPFLOWY_HOST: https://appflowy.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      main:
        controller: *app
        ports:
          http:
            port: *port
