---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app linkwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        DATABASE_URL: "postgresql://${APP}:{{ .DB_PASSWORD }}@postgres-cluster-rw.database.svc.cluster.local/${APP}"
        AUTHENTIK_CLIENT_ID: "{{ .AUTHENTIK_CLIENT_ID }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .AUTHENTIK_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: linkwarden
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret linkwarden-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *secret
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_PASS: '{{ .DB_PASSWORD }}'
        INIT_POSTGRES_SUPER_USER: '{{ .POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  dataFrom:
    - extract:
        key: linkwarden
    - extract:
        key: cloudnative_pg
