apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZiKltprpfFcrP18=,iv:R4h/ctQLzwmcXnT487mWNqCTHbKZtLno3MwZtQc2RtA=,tag:V62Ydoiwm61WUwUgI7vzOA==,type:str]
sops:
  age:
    - recipient: age1yu7mnjc625umxhznmkc8yc3mhgzn9g9n54jwarrp3l23ja90m54q0l5yw4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudUMxOWhGaUhKWjNpcWVQ
        NHBKQklHR3Q1bzBHSkRmMEFvdVdiS3g0YWdVCkZWL1BLbVQ2dlRvTzdLMWhiWVRu
        L2djTDU2UG9RVVdOa2dMZkV3b1F3VUEKLS0tIFczSzNLQ25UME5hQXB3a3UzTlhp
        MWFDT1Y1ZkxQVnhoZTVneEF3T2F4aUUKcibTi74lCEr7iaP1q0MoBif9S/oQ3KgW
        Yh9mrr02v9T9vn27QUClLNiBQm450IJpetdl0mIt8kmt3RIo8BtC4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T16:00:29Z"
  mac: ENC[AES256_GCM,data:DLEOIZU/Z3I2f+rd6Cx53NP5HIEYaM80HcprLVMdaWjcH7lTcn5N7ozapIjjkCjh19KT69UKEunohQwB0ia92fwwTwqbyUHAwp+mBIYtTVvC9+8M6ZQexD0R+2UOkU7Ai/k7Kk5jm65EMBAUg2uJuPHxkijRfpb7NB6YS8k1cME=,iv:S3REkLj5KfQJF/kcse4qXJhT77IM4gsPjedh1rGcD08=,tag:z1KL/W1Z20TwmzjZftEWRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
