---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openebs
  install:
    disableHooks: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    disableHooks: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: true
      replicated:
        mayastor:
          enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: true
          keep: true
    localpv-provisioner:
      localpv:
        image:
          registry: quay.io/
        basePath: &hostPath /var/mnt/local-hostpath
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: *hostPath
      helperPod:
        image:
          registry: quay.io/
    zfs-localpv:
      enabled: true
      zfsNode:
        encrKeysDir: /var/openebs/keys
      crds:
        zfsLocalPv:
          enabled: true
        csi:
          volumeSnapshots:
            enabled: true
    loki:
      enabled: false
    alloy:
      enabled: false
    minio:
      enabled: false
